# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import packages_pb2 as packages__pb2


class PackageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListAvailablePackages = channel.unary_stream(
        '/rqt2.api.v1.PackageService/ListAvailablePackages',
        request_serializer=packages__pb2.ListPackagesRequest.SerializeToString,
        response_deserializer=packages__pb2.PackageInfo.FromString,
        )
    self.InstallPackage = channel.unary_stream(
        '/rqt2.api.v1.PackageService/InstallPackage',
        request_serializer=packages__pb2.InstallRequest.SerializeToString,
        response_deserializer=packages__pb2.InstallProgress.FromString,
        )


class PackageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListAvailablePackages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InstallPackage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PackageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListAvailablePackages': grpc.unary_stream_rpc_method_handler(
          servicer.ListAvailablePackages,
          request_deserializer=packages__pb2.ListPackagesRequest.FromString,
          response_serializer=packages__pb2.PackageInfo.SerializeToString,
      ),
      'InstallPackage': grpc.unary_stream_rpc_method_handler(
          servicer.InstallPackage,
          request_deserializer=packages__pb2.InstallRequest.FromString,
          response_serializer=packages__pb2.InstallProgress.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rqt2.api.v1.PackageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
