# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packages.proto',
  package='rqt2.api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x0epackages.proto\x12\x0brqt2.api.v1\"%\n\x13ListPackagesRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"W\n\x0bPackageInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0cis_installed\x18\x04 \x01(\x08\"&\n\x0eInstallRequest\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\"5\n\x0fInstallProgress\x12\x10\n\x08log_line\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x02\x32\xb6\x01\n\x0ePackageService\x12U\n\x15ListAvailablePackages\x12 .rqt2.api.v1.ListPackagesRequest\x1a\x18.rqt2.api.v1.PackageInfo0\x01\x12M\n\x0eInstallPackage\x12\x1b.rqt2.api.v1.InstallRequest\x1a\x1c.rqt2.api.v1.InstallProgress0\x01\x62\x06proto3')
)




_LISTPACKAGESREQUEST = _descriptor.Descriptor(
  name='ListPackagesRequest',
  full_name='rqt2.api.v1.ListPackagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='rqt2.api.v1.ListPackagesRequest.filter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=68,
)


_PACKAGEINFO = _descriptor.Descriptor(
  name='PackageInfo',
  full_name='rqt2.api.v1.PackageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rqt2.api.v1.PackageInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='rqt2.api.v1.PackageInfo.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='rqt2.api.v1.PackageInfo.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_installed', full_name='rqt2.api.v1.PackageInfo.is_installed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=157,
)


_INSTALLREQUEST = _descriptor.Descriptor(
  name='InstallRequest',
  full_name='rqt2.api.v1.InstallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_name', full_name='rqt2.api.v1.InstallRequest.package_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=197,
)


_INSTALLPROGRESS = _descriptor.Descriptor(
  name='InstallProgress',
  full_name='rqt2.api.v1.InstallProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_line', full_name='rqt2.api.v1.InstallProgress.log_line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='progress', full_name='rqt2.api.v1.InstallProgress.progress', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=252,
)

DESCRIPTOR.message_types_by_name['ListPackagesRequest'] = _LISTPACKAGESREQUEST
DESCRIPTOR.message_types_by_name['PackageInfo'] = _PACKAGEINFO
DESCRIPTOR.message_types_by_name['InstallRequest'] = _INSTALLREQUEST
DESCRIPTOR.message_types_by_name['InstallProgress'] = _INSTALLPROGRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListPackagesRequest = _reflection.GeneratedProtocolMessageType('ListPackagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTPACKAGESREQUEST,
  __module__ = 'packages_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.ListPackagesRequest)
  ))
_sym_db.RegisterMessage(ListPackagesRequest)

PackageInfo = _reflection.GeneratedProtocolMessageType('PackageInfo', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGEINFO,
  __module__ = 'packages_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.PackageInfo)
  ))
_sym_db.RegisterMessage(PackageInfo)

InstallRequest = _reflection.GeneratedProtocolMessageType('InstallRequest', (_message.Message,), dict(
  DESCRIPTOR = _INSTALLREQUEST,
  __module__ = 'packages_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.InstallRequest)
  ))
_sym_db.RegisterMessage(InstallRequest)

InstallProgress = _reflection.GeneratedProtocolMessageType('InstallProgress', (_message.Message,), dict(
  DESCRIPTOR = _INSTALLPROGRESS,
  __module__ = 'packages_pb2'
  # @@protoc_insertion_point(class_scope:rqt2.api.v1.InstallProgress)
  ))
_sym_db.RegisterMessage(InstallProgress)



_PACKAGESERVICE = _descriptor.ServiceDescriptor(
  name='PackageService',
  full_name='rqt2.api.v1.PackageService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=255,
  serialized_end=437,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListAvailablePackages',
    full_name='rqt2.api.v1.PackageService.ListAvailablePackages',
    index=0,
    containing_service=None,
    input_type=_LISTPACKAGESREQUEST,
    output_type=_PACKAGEINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InstallPackage',
    full_name='rqt2.api.v1.PackageService.InstallPackage',
    index=1,
    containing_service=None,
    input_type=_INSTALLREQUEST,
    output_type=_INSTALLPROGRESS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PACKAGESERVICE)

DESCRIPTOR.services_by_name['PackageService'] = _PACKAGESERVICE

# @@protoc_insertion_point(module_scope)
